### ISSUE TITLE
messages containing URLs aren't clickable on iOS and Web

### ISSUE THREAD

**Issue by Cadair** [tulir/mautrix-hangouts#9]
I sent a message to hangouts across the bridge which was just a URL. I was then told that someone else using the iOS client couldn't click the link, it just showed up as normal text. It was clickable on Android.

**Comment by bobpaul** [comment]
This issue isn't iOS specific. Log into https://hangouts.google.com or https://gmail.com and you'll see you often can't click you URLs you've sent there, either. Android's Hangouts client seems to have its own logic to detect and convert URLs into clickable links.

I don't think this is broken 100% reproducible, either, but I haven't methodically tested it.

I don't see any corresponding bug in Hangups, but that's probably the first thing to test.

**Comment by joao-p-marques** [comment]
Hi. This issue keeps happening. In my case:
1. I send a message from Matrix with a URL
2. Open the chat on https://hangouts.google.com or https://gmail.com and don't see the text as URL.

![image](https://user-images.githubusercontent.com/38977934/94266208-18f33700-ff3a-11ea-9f1a-f20f5debce36.png)

![image](https://user-images.githubusercontent.com/38977934/94265988-ba2dbd80-ff39-11ea-9a2f-40cec8aadd77.png)

When I open on Android using the app, I can see the text formatted as URL, however, but I guess that can also have to do with Android himself reformatting, right?

**Comment by joao-p-marques** [comment]
Hi. Has any progress been made on this? 

Or could someone point a direction por a potential PR for fixing this?
